openapi: 3.1.0
info:
  version: 1.0.0
  title: AquaTracker app
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: |
    This is a documentation of AquaTracker app
servers:
  - url: https://aquatracker-node.onrender.com
tags:
  - name: Users
    description: Operations with user.
  - name: Water
    description: Operations related to water consumption.
paths:
  /users/register:
    post:
      $ref: ../swagger/paths/users/register/post.yaml
  /users/login:
    post:
      $ref: ../swagger/paths/users/login/post.yaml
  /users/refresh:
    post:
      $ref: ../swagger/paths/users/refresh/post.yaml
  /users/update:
    patch:
      $ref: ../swagger/paths/users/update/patch.yaml
  /users/logout:
    post:
      $ref: ../swagger/paths/users/logout/post.yaml
  /users/current:
    get:
      $ref: ../swagger/paths/users/current/get.yaml
  /users/count:
    get:
      $ref: ../swagger/paths/users/count/get.yaml
  /water:
    get:
      $ref: ../swagger/paths/water/get.yaml
    post:
      $ref: ../swagger/paths/water/post.yaml
  /water/{id}:
    patch:
      $ref: ../swagger/paths/water/{id}/patch.yaml
    delete:
      $ref: ../swagger/paths/water/{id}/delete.yaml
  /water/day/{date}:
    get:
      $ref: ../swagger/paths/water/day/{date}/get.yaml
  /water/month/{date}:
    get:
      $ref: ../swagger/paths/water/month/{date}/get.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
